<?php
/**
 * ChatsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  BotixPro\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BOTIX Public API
 *
 * Публичный программный интерфейс платформы BOTIX (botix.pro) — позволяет интеграторам и сторонним разработчикам встраивать функционал BOTIX в свои продукты: магазины, CRM, мобильные приложения, бэкенды.  **Авторизация:** заголовок `Authorization: Bearer btx_live_…`. Каждый ключ привязан к одному `project_id`. Каждый ключ имеет список `scopes` — операций, которые им разрешены. Без нужного scope — `403 INSUFFICIENT_SCOPE`.  **Гейтинг по тарифу:** - тариф без `api_enabled` — `403 API_NOT_AVAILABLE_ON_PLAN` - триальный тариф (`api_write_enabled=0`) — read-only, POST/PUT/PATCH/DELETE → `403 TRIAL_READ_ONLY` - лимиты `api_rate_per_minute` / `api_rate_per_day` — из настроек тарифа (см. ЛК `/billing`)  **Стандарт ответов:** обёртка `{success, data, meta}` для успеха и `{success:false, error:{code,message,details}}` для ошибки.  **Версионирование:** `/public/v1/_*` фиксирован. Новые поля в ответах могут добавляться, удаление/смена типов запрещены.  ## Что нового в 1.1.0 (2026-05-22)  - **Rate-limit заголовки** во всех ответах: `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset`. На 429 — дополнительно `Retry-After`. - **Cursor-based пагинация** — query-параметр `cursor` + поле `meta.next_cursor` параллельно с существующим `page`/`per_page` (старые клиенты не ломаются). - **Bulk endpoints** для интеграторов: `POST /contacts/bulk-create`, `POST /messages/bulk-send`, `POST /contacts/bulk-update` (до 100 операций за запрос, частичный успех).  Изменения обратно-совместимые: все endpoint v1.0 работают без правок на стороне клиента.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: hello@botix.pro
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BotixPro\Sdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use BotixPro\Sdk\ApiException;
use BotixPro\Sdk\Configuration;
use BotixPro\Sdk\FormDataProcessor;
use BotixPro\Sdk\HeaderSelector;
use BotixPro\Sdk\ObjectSerializer;

/**
 * ChatsApi Class Doc Comment
 *
 * @category Class
 * @package  BotixPro\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ChatsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'chatsList' => [
            'application/json',
        ],
        'chatsMessages' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation chatsList
     *
     * Список чатов
     *
     * @param  int|null $page page (optional, default to 1)
     * @param  int|null $per_page per_page (optional, default to 50)
     * @param  string|null $cursor v1.1+. Opaque cursor для постраничной выборки. Если передан — параметры &#x60;page&#x60;/&#x60;per_page&#x60; игнорируются. Получите следующий cursor из &#x60;meta.next_cursor&#x60; предыдущего ответа. &#x60;null&#x60;/отсутствие &#x60;next_cursor&#x60; &#x3D; последняя страница. (optional)
     * @param  int|null $limit v1.1+. Размер cursor-страницы. Используется только в cursor-режиме (&#x60;?cursor&#x3D;...&#x60;); для классической page-пагинации применяется &#x60;per_page&#x60;. (optional, default to 50)
     * @param  string|null $status status (optional)
     * @param  string|null $channel channel (optional)
     * @param  int|null $contact_id contact_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chatsList'] to see the possible values for this operation
     *
     * @throws \BotixPro\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \BotixPro\Sdk\Model\ChatsList200Response
     */
    public function chatsList($page = 1, $per_page = 50, $cursor = null, $limit = 50, $status = null, $channel = null, $contact_id = null, string $contentType = self::contentTypes['chatsList'][0])
    {
        list($response) = $this->chatsListWithHttpInfo($page, $per_page, $cursor, $limit, $status, $channel, $contact_id, $contentType);
        return $response;
    }

    /**
     * Operation chatsListWithHttpInfo
     *
     * Список чатов
     *
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 50)
     * @param  string|null $cursor v1.1+. Opaque cursor для постраничной выборки. Если передан — параметры &#x60;page&#x60;/&#x60;per_page&#x60; игнорируются. Получите следующий cursor из &#x60;meta.next_cursor&#x60; предыдущего ответа. &#x60;null&#x60;/отсутствие &#x60;next_cursor&#x60; &#x3D; последняя страница. (optional)
     * @param  int|null $limit v1.1+. Размер cursor-страницы. Используется только в cursor-режиме (&#x60;?cursor&#x3D;...&#x60;); для классической page-пагинации применяется &#x60;per_page&#x60;. (optional, default to 50)
     * @param  string|null $status (optional)
     * @param  string|null $channel (optional)
     * @param  int|null $contact_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chatsList'] to see the possible values for this operation
     *
     * @throws \BotixPro\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \BotixPro\Sdk\Model\ChatsList200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function chatsListWithHttpInfo($page = 1, $per_page = 50, $cursor = null, $limit = 50, $status = null, $channel = null, $contact_id = null, string $contentType = self::contentTypes['chatsList'][0])
    {
        $request = $this->chatsListRequest($page, $per_page, $cursor, $limit, $status, $channel, $contact_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\BotixPro\Sdk\Model\ChatsList200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\BotixPro\Sdk\Model\ChatsList200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BotixPro\Sdk\Model\ChatsList200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation chatsListAsync
     *
     * Список чатов
     *
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 50)
     * @param  string|null $cursor v1.1+. Opaque cursor для постраничной выборки. Если передан — параметры &#x60;page&#x60;/&#x60;per_page&#x60; игнорируются. Получите следующий cursor из &#x60;meta.next_cursor&#x60; предыдущего ответа. &#x60;null&#x60;/отсутствие &#x60;next_cursor&#x60; &#x3D; последняя страница. (optional)
     * @param  int|null $limit v1.1+. Размер cursor-страницы. Используется только в cursor-режиме (&#x60;?cursor&#x3D;...&#x60;); для классической page-пагинации применяется &#x60;per_page&#x60;. (optional, default to 50)
     * @param  string|null $status (optional)
     * @param  string|null $channel (optional)
     * @param  int|null $contact_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chatsList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatsListAsync($page = 1, $per_page = 50, $cursor = null, $limit = 50, $status = null, $channel = null, $contact_id = null, string $contentType = self::contentTypes['chatsList'][0])
    {
        return $this->chatsListAsyncWithHttpInfo($page, $per_page, $cursor, $limit, $status, $channel, $contact_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation chatsListAsyncWithHttpInfo
     *
     * Список чатов
     *
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 50)
     * @param  string|null $cursor v1.1+. Opaque cursor для постраничной выборки. Если передан — параметры &#x60;page&#x60;/&#x60;per_page&#x60; игнорируются. Получите следующий cursor из &#x60;meta.next_cursor&#x60; предыдущего ответа. &#x60;null&#x60;/отсутствие &#x60;next_cursor&#x60; &#x3D; последняя страница. (optional)
     * @param  int|null $limit v1.1+. Размер cursor-страницы. Используется только в cursor-режиме (&#x60;?cursor&#x3D;...&#x60;); для классической page-пагинации применяется &#x60;per_page&#x60;. (optional, default to 50)
     * @param  string|null $status (optional)
     * @param  string|null $channel (optional)
     * @param  int|null $contact_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chatsList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatsListAsyncWithHttpInfo($page = 1, $per_page = 50, $cursor = null, $limit = 50, $status = null, $channel = null, $contact_id = null, string $contentType = self::contentTypes['chatsList'][0])
    {
        $returnType = '\BotixPro\Sdk\Model\ChatsList200Response';
        $request = $this->chatsListRequest($page, $per_page, $cursor, $limit, $status, $channel, $contact_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'chatsList'
     *
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 50)
     * @param  string|null $cursor v1.1+. Opaque cursor для постраничной выборки. Если передан — параметры &#x60;page&#x60;/&#x60;per_page&#x60; игнорируются. Получите следующий cursor из &#x60;meta.next_cursor&#x60; предыдущего ответа. &#x60;null&#x60;/отсутствие &#x60;next_cursor&#x60; &#x3D; последняя страница. (optional)
     * @param  int|null $limit v1.1+. Размер cursor-страницы. Используется только в cursor-режиме (&#x60;?cursor&#x3D;...&#x60;); для классической page-пагинации применяется &#x60;per_page&#x60;. (optional, default to 50)
     * @param  string|null $status (optional)
     * @param  string|null $channel (optional)
     * @param  int|null $contact_id (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chatsList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function chatsListRequest($page = 1, $per_page = 50, $cursor = null, $limit = 50, $status = null, $channel = null, $contact_id = null, string $contentType = self::contentTypes['chatsList'][0])
    {

        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling ChatsApi.chatsList, must be bigger than or equal to 1.');
        }
        
        if ($per_page !== null && $per_page > 100) {
            throw new \InvalidArgumentException('invalid value for "$per_page" when calling ChatsApi.chatsList, must be smaller than or equal to 100.');
        }
        if ($per_page !== null && $per_page < 1) {
            throw new \InvalidArgumentException('invalid value for "$per_page" when calling ChatsApi.chatsList, must be bigger than or equal to 1.');
        }
        

        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ChatsApi.chatsList, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ChatsApi.chatsList, must be bigger than or equal to 1.');
        }
        




        $resourcePath = '/public/v1/chats';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $per_page,
            'per_page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cursor,
            'cursor', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status,
            'status', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $channel,
            'channel', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $contact_id,
            'contact_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (btx_live_<40-char-alnum>) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation chatsMessages
     *
     * Сообщения внутри чата
     *
     * @param  int $id id (required)
     * @param  int|null $page page (optional, default to 1)
     * @param  int|null $per_page per_page (optional, default to 50)
     * @param  string|null $cursor v1.1+. Opaque cursor для постраничной выборки. Если передан — параметры &#x60;page&#x60;/&#x60;per_page&#x60; игнорируются. Получите следующий cursor из &#x60;meta.next_cursor&#x60; предыдущего ответа. &#x60;null&#x60;/отсутствие &#x60;next_cursor&#x60; &#x3D; последняя страница. (optional)
     * @param  int|null $limit v1.1+. Размер cursor-страницы. Используется только в cursor-режиме (&#x60;?cursor&#x3D;...&#x60;); для классической page-пагинации применяется &#x60;per_page&#x60;. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chatsMessages'] to see the possible values for this operation
     *
     * @throws \BotixPro\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \BotixPro\Sdk\Model\MessagesList200Response|\BotixPro\Sdk\Model\Error
     */
    public function chatsMessages($id, $page = 1, $per_page = 50, $cursor = null, $limit = 50, string $contentType = self::contentTypes['chatsMessages'][0])
    {
        list($response) = $this->chatsMessagesWithHttpInfo($id, $page, $per_page, $cursor, $limit, $contentType);
        return $response;
    }

    /**
     * Operation chatsMessagesWithHttpInfo
     *
     * Сообщения внутри чата
     *
     * @param  int $id (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 50)
     * @param  string|null $cursor v1.1+. Opaque cursor для постраничной выборки. Если передан — параметры &#x60;page&#x60;/&#x60;per_page&#x60; игнорируются. Получите следующий cursor из &#x60;meta.next_cursor&#x60; предыдущего ответа. &#x60;null&#x60;/отсутствие &#x60;next_cursor&#x60; &#x3D; последняя страница. (optional)
     * @param  int|null $limit v1.1+. Размер cursor-страницы. Используется только в cursor-режиме (&#x60;?cursor&#x3D;...&#x60;); для классической page-пагинации применяется &#x60;per_page&#x60;. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chatsMessages'] to see the possible values for this operation
     *
     * @throws \BotixPro\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \BotixPro\Sdk\Model\MessagesList200Response|\BotixPro\Sdk\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function chatsMessagesWithHttpInfo($id, $page = 1, $per_page = 50, $cursor = null, $limit = 50, string $contentType = self::contentTypes['chatsMessages'][0])
    {
        $request = $this->chatsMessagesRequest($id, $page, $per_page, $cursor, $limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\BotixPro\Sdk\Model\MessagesList200Response',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\BotixPro\Sdk\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\BotixPro\Sdk\Model\MessagesList200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BotixPro\Sdk\Model\MessagesList200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BotixPro\Sdk\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation chatsMessagesAsync
     *
     * Сообщения внутри чата
     *
     * @param  int $id (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 50)
     * @param  string|null $cursor v1.1+. Opaque cursor для постраничной выборки. Если передан — параметры &#x60;page&#x60;/&#x60;per_page&#x60; игнорируются. Получите следующий cursor из &#x60;meta.next_cursor&#x60; предыдущего ответа. &#x60;null&#x60;/отсутствие &#x60;next_cursor&#x60; &#x3D; последняя страница. (optional)
     * @param  int|null $limit v1.1+. Размер cursor-страницы. Используется только в cursor-режиме (&#x60;?cursor&#x3D;...&#x60;); для классической page-пагинации применяется &#x60;per_page&#x60;. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chatsMessages'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatsMessagesAsync($id, $page = 1, $per_page = 50, $cursor = null, $limit = 50, string $contentType = self::contentTypes['chatsMessages'][0])
    {
        return $this->chatsMessagesAsyncWithHttpInfo($id, $page, $per_page, $cursor, $limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation chatsMessagesAsyncWithHttpInfo
     *
     * Сообщения внутри чата
     *
     * @param  int $id (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 50)
     * @param  string|null $cursor v1.1+. Opaque cursor для постраничной выборки. Если передан — параметры &#x60;page&#x60;/&#x60;per_page&#x60; игнорируются. Получите следующий cursor из &#x60;meta.next_cursor&#x60; предыдущего ответа. &#x60;null&#x60;/отсутствие &#x60;next_cursor&#x60; &#x3D; последняя страница. (optional)
     * @param  int|null $limit v1.1+. Размер cursor-страницы. Используется только в cursor-режиме (&#x60;?cursor&#x3D;...&#x60;); для классической page-пагинации применяется &#x60;per_page&#x60;. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chatsMessages'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function chatsMessagesAsyncWithHttpInfo($id, $page = 1, $per_page = 50, $cursor = null, $limit = 50, string $contentType = self::contentTypes['chatsMessages'][0])
    {
        $returnType = '\BotixPro\Sdk\Model\MessagesList200Response';
        $request = $this->chatsMessagesRequest($id, $page, $per_page, $cursor, $limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'chatsMessages'
     *
     * @param  int $id (required)
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 50)
     * @param  string|null $cursor v1.1+. Opaque cursor для постраничной выборки. Если передан — параметры &#x60;page&#x60;/&#x60;per_page&#x60; игнорируются. Получите следующий cursor из &#x60;meta.next_cursor&#x60; предыдущего ответа. &#x60;null&#x60;/отсутствие &#x60;next_cursor&#x60; &#x3D; последняя страница. (optional)
     * @param  int|null $limit v1.1+. Размер cursor-страницы. Используется только в cursor-режиме (&#x60;?cursor&#x3D;...&#x60;); для классической page-пагинации применяется &#x60;per_page&#x60;. (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['chatsMessages'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function chatsMessagesRequest($id, $page = 1, $per_page = 50, $cursor = null, $limit = 50, string $contentType = self::contentTypes['chatsMessages'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling chatsMessages'
            );
        }

        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling ChatsApi.chatsMessages, must be bigger than or equal to 1.');
        }
        
        if ($per_page !== null && $per_page > 100) {
            throw new \InvalidArgumentException('invalid value for "$per_page" when calling ChatsApi.chatsMessages, must be smaller than or equal to 100.');
        }
        if ($per_page !== null && $per_page < 1) {
            throw new \InvalidArgumentException('invalid value for "$per_page" when calling ChatsApi.chatsMessages, must be bigger than or equal to 1.');
        }
        

        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ChatsApi.chatsMessages, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ChatsApi.chatsMessages, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/public/v1/chats/{id}/messages';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $per_page,
            'per_page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cursor,
            'cursor', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{id}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (btx_live_<40-char-alnum>) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
