<?php
/**
 * MessagesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  BotixPro\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BOTIX Public API
 *
 * Публичный программный интерфейс платформы BOTIX (botix.pro) — позволяет интеграторам и сторонним разработчикам встраивать функционал BOTIX в свои продукты: магазины, CRM, мобильные приложения, бэкенды.  **Авторизация:** заголовок `Authorization: Bearer btx_live_…`. Каждый ключ привязан к одному `project_id`. Каждый ключ имеет список `scopes` — операций, которые им разрешены. Без нужного scope — `403 INSUFFICIENT_SCOPE`.  **Гейтинг по тарифу:** - тариф без `api_enabled` — `403 API_NOT_AVAILABLE_ON_PLAN` - триальный тариф (`api_write_enabled=0`) — read-only, POST/PUT/PATCH/DELETE → `403 TRIAL_READ_ONLY` - лимиты `api_rate_per_minute` / `api_rate_per_day` — из настроек тарифа (см. ЛК `/billing`)  **Стандарт ответов:** обёртка `{success, data, meta}` для успеха и `{success:false, error:{code,message,details}}` для ошибки.  **Версионирование:** `/public/v1/_*` фиксирован. Новые поля в ответах могут добавляться, удаление/смена типов запрещены.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@botix.pro
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BotixPro\Sdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use BotixPro\Sdk\ApiException;
use BotixPro\Sdk\Configuration;
use BotixPro\Sdk\FormDataProcessor;
use BotixPro\Sdk\HeaderSelector;
use BotixPro\Sdk\ObjectSerializer;

/**
 * MessagesApi Class Doc Comment
 *
 * @category Class
 * @package  BotixPro\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MessagesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'messagesList' => [
            'application/json',
        ],
        'messagesSend' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation messagesList
     *
     * История сообщений
     *
     * @param  int|null $page page (optional, default to 1)
     * @param  int|null $per_page per_page (optional, default to 50)
     * @param  int|null $contact_id contact_id (optional)
     * @param  int|null $chat_id alias для conversation_id (optional)
     * @param  string|null $channel channel (optional)
     * @param  string|null $role role (optional)
     * @param  \DateTime|null $since since (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['messagesList'] to see the possible values for this operation
     *
     * @throws \BotixPro\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \BotixPro\Sdk\Model\MessagesList200Response
     */
    public function messagesList($page = 1, $per_page = 50, $contact_id = null, $chat_id = null, $channel = null, $role = null, $since = null, string $contentType = self::contentTypes['messagesList'][0])
    {
        list($response) = $this->messagesListWithHttpInfo($page, $per_page, $contact_id, $chat_id, $channel, $role, $since, $contentType);
        return $response;
    }

    /**
     * Operation messagesListWithHttpInfo
     *
     * История сообщений
     *
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 50)
     * @param  int|null $contact_id (optional)
     * @param  int|null $chat_id alias для conversation_id (optional)
     * @param  string|null $channel (optional)
     * @param  string|null $role (optional)
     * @param  \DateTime|null $since (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['messagesList'] to see the possible values for this operation
     *
     * @throws \BotixPro\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \BotixPro\Sdk\Model\MessagesList200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function messagesListWithHttpInfo($page = 1, $per_page = 50, $contact_id = null, $chat_id = null, $channel = null, $role = null, $since = null, string $contentType = self::contentTypes['messagesList'][0])
    {
        $request = $this->messagesListRequest($page, $per_page, $contact_id, $chat_id, $channel, $role, $since, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\BotixPro\Sdk\Model\MessagesList200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\BotixPro\Sdk\Model\MessagesList200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BotixPro\Sdk\Model\MessagesList200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation messagesListAsync
     *
     * История сообщений
     *
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 50)
     * @param  int|null $contact_id (optional)
     * @param  int|null $chat_id alias для conversation_id (optional)
     * @param  string|null $channel (optional)
     * @param  string|null $role (optional)
     * @param  \DateTime|null $since (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['messagesList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function messagesListAsync($page = 1, $per_page = 50, $contact_id = null, $chat_id = null, $channel = null, $role = null, $since = null, string $contentType = self::contentTypes['messagesList'][0])
    {
        return $this->messagesListAsyncWithHttpInfo($page, $per_page, $contact_id, $chat_id, $channel, $role, $since, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation messagesListAsyncWithHttpInfo
     *
     * История сообщений
     *
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 50)
     * @param  int|null $contact_id (optional)
     * @param  int|null $chat_id alias для conversation_id (optional)
     * @param  string|null $channel (optional)
     * @param  string|null $role (optional)
     * @param  \DateTime|null $since (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['messagesList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function messagesListAsyncWithHttpInfo($page = 1, $per_page = 50, $contact_id = null, $chat_id = null, $channel = null, $role = null, $since = null, string $contentType = self::contentTypes['messagesList'][0])
    {
        $returnType = '\BotixPro\Sdk\Model\MessagesList200Response';
        $request = $this->messagesListRequest($page, $per_page, $contact_id, $chat_id, $channel, $role, $since, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'messagesList'
     *
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $per_page (optional, default to 50)
     * @param  int|null $contact_id (optional)
     * @param  int|null $chat_id alias для conversation_id (optional)
     * @param  string|null $channel (optional)
     * @param  string|null $role (optional)
     * @param  \DateTime|null $since (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['messagesList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function messagesListRequest($page = 1, $per_page = 50, $contact_id = null, $chat_id = null, $channel = null, $role = null, $since = null, string $contentType = self::contentTypes['messagesList'][0])
    {

        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling MessagesApi.messagesList, must be bigger than or equal to 1.');
        }
        
        if ($per_page !== null && $per_page > 100) {
            throw new \InvalidArgumentException('invalid value for "$per_page" when calling MessagesApi.messagesList, must be smaller than or equal to 100.');
        }
        if ($per_page !== null && $per_page < 1) {
            throw new \InvalidArgumentException('invalid value for "$per_page" when calling MessagesApi.messagesList, must be bigger than or equal to 1.');
        }
        






        $resourcePath = '/public/v1/messages';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $per_page,
            'per_page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $contact_id,
            'contact_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $chat_id,
            'chat_id', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $channel,
            'channel', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $role,
            'role', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $since,
            'since', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (btx_live_<40-char-alnum>) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation messagesSend
     *
     * Отправить сообщение
     *
     * @param  \BotixPro\Sdk\Model\MessagesSendRequest $messages_send_request messages_send_request (required)
     * @param  string|null $idempotency_key Уникальный токен запроса для защиты от дублей при сетевых сбоях. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['messagesSend'] to see the possible values for this operation
     *
     * @throws \BotixPro\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \BotixPro\Sdk\Model\MessagesSend200Response|\BotixPro\Sdk\Model\Error|\BotixPro\Sdk\Model\Error
     */
    public function messagesSend($messages_send_request, $idempotency_key = null, string $contentType = self::contentTypes['messagesSend'][0])
    {
        list($response) = $this->messagesSendWithHttpInfo($messages_send_request, $idempotency_key, $contentType);
        return $response;
    }

    /**
     * Operation messagesSendWithHttpInfo
     *
     * Отправить сообщение
     *
     * @param  \BotixPro\Sdk\Model\MessagesSendRequest $messages_send_request (required)
     * @param  string|null $idempotency_key Уникальный токен запроса для защиты от дублей при сетевых сбоях. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['messagesSend'] to see the possible values for this operation
     *
     * @throws \BotixPro\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \BotixPro\Sdk\Model\MessagesSend200Response|\BotixPro\Sdk\Model\Error|\BotixPro\Sdk\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function messagesSendWithHttpInfo($messages_send_request, $idempotency_key = null, string $contentType = self::contentTypes['messagesSend'][0])
    {
        $request = $this->messagesSendRequest($messages_send_request, $idempotency_key, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\BotixPro\Sdk\Model\MessagesSend200Response',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\BotixPro\Sdk\Model\Error',
                        $request,
                        $response,
                    );
                case 502:
                    return $this->handleResponseWithDataType(
                        '\BotixPro\Sdk\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\BotixPro\Sdk\Model\MessagesSend200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BotixPro\Sdk\Model\MessagesSend200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BotixPro\Sdk\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 502:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\BotixPro\Sdk\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation messagesSendAsync
     *
     * Отправить сообщение
     *
     * @param  \BotixPro\Sdk\Model\MessagesSendRequest $messages_send_request (required)
     * @param  string|null $idempotency_key Уникальный токен запроса для защиты от дублей при сетевых сбоях. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['messagesSend'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function messagesSendAsync($messages_send_request, $idempotency_key = null, string $contentType = self::contentTypes['messagesSend'][0])
    {
        return $this->messagesSendAsyncWithHttpInfo($messages_send_request, $idempotency_key, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation messagesSendAsyncWithHttpInfo
     *
     * Отправить сообщение
     *
     * @param  \BotixPro\Sdk\Model\MessagesSendRequest $messages_send_request (required)
     * @param  string|null $idempotency_key Уникальный токен запроса для защиты от дублей при сетевых сбоях. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['messagesSend'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function messagesSendAsyncWithHttpInfo($messages_send_request, $idempotency_key = null, string $contentType = self::contentTypes['messagesSend'][0])
    {
        $returnType = '\BotixPro\Sdk\Model\MessagesSend200Response';
        $request = $this->messagesSendRequest($messages_send_request, $idempotency_key, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'messagesSend'
     *
     * @param  \BotixPro\Sdk\Model\MessagesSendRequest $messages_send_request (required)
     * @param  string|null $idempotency_key Уникальный токен запроса для защиты от дублей при сетевых сбоях. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['messagesSend'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function messagesSendRequest($messages_send_request, $idempotency_key = null, string $contentType = self::contentTypes['messagesSend'][0])
    {

        // verify the required parameter 'messages_send_request' is set
        if ($messages_send_request === null || (is_array($messages_send_request) && count($messages_send_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $messages_send_request when calling messagesSend'
            );
        }

        if ($idempotency_key !== null && strlen($idempotency_key) > 255) {
            throw new \InvalidArgumentException('invalid length for "$idempotency_key" when calling MessagesApi.messagesSend, must be smaller than or equal to 255.');
        }
        

        $resourcePath = '/public/v1/messages';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($idempotency_key !== null) {
            $headerParams['Idempotency-Key'] = ObjectSerializer::toHeaderValue($idempotency_key);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($messages_send_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($messages_send_request));
            } else {
                $httpBody = $messages_send_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (btx_live_<40-char-alnum>) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
