<?php
/**
 * WebhookEvent
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  BotixPro\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BOTIX Public API
 *
 * Публичный программный интерфейс платформы BOTIX (botix.pro) — позволяет интеграторам и сторонним разработчикам встраивать функционал BOTIX в свои продукты: магазины, CRM, мобильные приложения, бэкенды.  **Авторизация:** заголовок `Authorization: Bearer btx_live_…`. Каждый ключ привязан к одному `project_id`. Каждый ключ имеет список `scopes` — операций, которые им разрешены. Без нужного scope — `403 INSUFFICIENT_SCOPE`.  **Гейтинг по тарифу:** - тариф без `api_enabled` — `403 API_NOT_AVAILABLE_ON_PLAN` - триальный тариф (`api_write_enabled=0`) — read-only, POST/PUT/PATCH/DELETE → `403 TRIAL_READ_ONLY` - лимиты `api_rate_per_minute` / `api_rate_per_day` — из настроек тарифа (см. ЛК `/billing`)  **Стандарт ответов:** обёртка `{success, data, meta}` для успеха и `{success:false, error:{code,message,details}}` для ошибки.  **Версионирование:** `/public/v1/_*` фиксирован. Новые поля в ответах могут добавляться, удаление/смена типов запрещены.  ## Что нового в 1.1.0 (2026-05-22)  - **Rate-limit заголовки** во всех ответах: `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset`. На 429 — дополнительно `Retry-After`. - **Cursor-based пагинация** — query-параметр `cursor` + поле `meta.next_cursor` параллельно с существующим `page`/`per_page` (старые клиенты не ломаются). - **Bulk endpoints** для интеграторов: `POST /contacts/bulk-create`, `POST /messages/bulk-send`, `POST /contacts/bulk-update` (до 100 операций за запрос, частичный успех).  Изменения обратно-совместимые: все endpoint v1.0 работают без правок на стороне клиента.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: hello@botix.pro
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BotixPro\Sdk\Model;
use \BotixPro\Sdk\ObjectSerializer;

/**
 * WebhookEvent Class Doc Comment
 *
 * @category Class
 * @package  BotixPro\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhookEvent
{
    /**
     * Possible values of this enum
     */
    public const CONTACT_CREATED = 'contact.created';

    public const CONTACT_UPDATED = 'contact.updated';

    public const CONTACT_DELETED = 'contact.deleted';

    public const CONTACT_TAGGED = 'contact.tagged';

    public const MESSAGE_RECEIVED = 'message.received';

    public const MESSAGE_SENT = 'message.sent';

    public const CHAT_OPENED = 'chat.opened';

    public const CHAT_CLOSED = 'chat.closed';

    public const CHAT_ASSIGNED = 'chat.assigned';

    public const SCENARIO_STARTED = 'scenario.started';

    public const SCENARIO_COMPLETED = 'scenario.completed';

    public const SCENARIO_FAILED = 'scenario.failed';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CONTACT_CREATED,
            self::CONTACT_UPDATED,
            self::CONTACT_DELETED,
            self::CONTACT_TAGGED,
            self::MESSAGE_RECEIVED,
            self::MESSAGE_SENT,
            self::CHAT_OPENED,
            self::CHAT_CLOSED,
            self::CHAT_ASSIGNED,
            self::SCENARIO_STARTED,
            self::SCENARIO_COMPLETED,
            self::SCENARIO_FAILED
        ];
    }
}


